/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmAluno.java
 *
 * Created on 19/06/2011, 16:53:14
 */
package presenca;
import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class frmAluno extends javax.swing.JPanel {
    Aluno aluno;
    dlgEditAluno editAluno;
    
    /** Creates new form frmAluno */
    public frmAluno() {
        initComponents();
        aluno = new Aluno();
        generateTable();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tlbAlunos = new javax.swing.JToolBar();
        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlunos = new javax.swing.JTable();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        tlbAlunos.setRollover(true);
        tlbAlunos.setMaximumSize(new java.awt.Dimension(32767, 30));

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presenca/resources/add.png"))); // NOI18N
        btnAdicionar.setText(" Adicionar ");
        btnAdicionar.setBorder(null);
        btnAdicionar.setFocusable(false);
        btnAdicionar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdicionar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        tlbAlunos.add(btnAdicionar);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presenca/resources/edit.png"))); // NOI18N
        btnEditar.setText(" Editar ");
        btnEditar.setBorder(null);
        btnEditar.setFocusable(false);
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        tlbAlunos.add(btnEditar);

        btnRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presenca/resources/delete.png"))); // NOI18N
        btnRemover.setText(" Remover ");
        btnRemover.setBorder(null);
        btnRemover.setFocusable(false);
        btnRemover.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRemover.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        tlbAlunos.add(btnRemover);

        add(tlbAlunos);

        tblAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nome", "Ano Ingresso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAlunos.setColumnSelectionAllowed(true);
        tblAlunos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblAlunos);
        tblAlunos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        editAluno = new dlgEditAluno(null,"Novo Aluno");
        editAluno.setVisible(true);
        generateTable();
}//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        Integer idAluno = tblAlunos.getSelectedRow();
        if(idAluno >= 0){
            String id = (String)tblAlunos.getValueAt(idAluno, 0);
            
            editAluno = new dlgEditAluno(null, "Editar Aluno", Integer.parseInt(id));
            editAluno.setVisible(true);
            generateTable();
        }else{
            JOptionPane.showMessageDialog(this, "Nenhum item foi selecionado.");
        }
}//GEN-LAST:event_btnEditarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        Integer idAluno = tblAlunos.getSelectedRow();
        if(idAluno >= 0){
            String id = (String)tblAlunos.getValueAt(idAluno, 0);
            
            int result = JOptionPane.showConfirmDialog(this,
                    "A ação de remoção não poderá ser desfeita.\nDeseja prosseguir?",
                    "Deseja remover o aluno?",
                    0);
            if(result == 0){
                aluno = new Aluno(Integer.parseInt(id));
                aluno.destroy();
                generateTable();
            }
            
        }else{
            JOptionPane.showMessageDialog(this, "Nenhum item foi selecionado.");
        }
}//GEN-LAST:event_btnRemoverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAlunos;
    private javax.swing.JToolBar tlbAlunos;
    // End of variables declaration//GEN-END:variables
    private void generateTable(){
        aluno.toTable(tblAlunos, "");
    }
}
