/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmEndereco.java
 *
 * Created on 18/06/2011, 20:23:57
 */
package presenca;

/**
 *
 * @author diego
 */
public class frmEndereco extends javax.swing.JPanel {
    private Endereco endereco;
    
    /** Creates new form frmEndereco */
    public frmEndereco() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogradouro = new javax.swing.JLabel();
        entLogradouro = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        entBairro = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        entNumero = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        entMunicipio = new javax.swing.JTextField();
        lblUf = new javax.swing.JLabel();
        entUf = new javax.swing.JTextField();
        lblCep = new javax.swing.JLabel();
        entCep = new javax.swing.JTextField();

        lblLogradouro.setText("Logradouro:");

        lblBairro.setText("Bairro:");

        lblNumero.setText("Número:");

        jLabel1.setText("Municipio:");

        lblUf.setText("UF:");

        lblCep.setText("CEP:");

        entCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entCepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCep)
                    .addComponent(lblBairro)
                    .addComponent(lblLogradouro)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(entBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblNumero))
                                    .addComponent(entMunicipio))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(lblUf)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(entUf, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(entNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))))
                            .addComponent(entLogradouro, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE))
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(entCep, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLogradouro)
                    .addComponent(entLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(entBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNumero)
                        .addComponent(entNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblBairro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(lblUf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCep)
                    .addComponent(entCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void entCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entCepActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField entBairro;
    private javax.swing.JTextField entCep;
    private javax.swing.JTextField entLogradouro;
    private javax.swing.JTextField entMunicipio;
    private javax.swing.JTextField entNumero;
    private javax.swing.JTextField entUf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblLogradouro;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblUf;
    // End of variables declaration//GEN-END:variables

    public Endereco getEndereco(){
        
        endereco.setBairro(entBairro.getText());
        endereco.setCep(entCep.getText());
        endereco.setLogradouro(entLogradouro.getText());
        endereco.setMunicipio(entMunicipio.getText());
        endereco.setNumero(entNumero.getText());
        endereco.setUf(entUf.getText());
        
        return endereco;
    }
    
    public void setEndereco(Endereco endereco){
        this.endereco = endereco;
        
        entBairro.setText(this.endereco.getBairro());
        entCep.setText(this.endereco.getCep());
        entLogradouro.setText(this.endereco.getLogradouro());
        entMunicipio.setText(this.endereco.getMunicipio());
        entNumero.setText(this.endereco.getNumero());
        entUf.setText(this.endereco.getUf());
    }
}
