/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmProfessor.java
 *
 * Created on 06/06/2011, 20:01:27
 */
package presenca;

/**
 *
 * @author diego
 */
public class frmProfessor extends javax.swing.JPanel {

    /** Creates new form frmProfessor */
    public frmProfessor() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tlbProfessores = new javax.swing.JToolBar();
        btnAdicionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProfessores = new javax.swing.JTable();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        tlbProfessores.setRollover(true);
        tlbProfessores.setMaximumSize(new java.awt.Dimension(32767, 30));

        btnAdicionar.setText("Adicionar");
        btnAdicionar.setFocusable(false);
        btnAdicionar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdicionar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/presenca/add_item_128.png"))); // NOI18N
        btnAdicionar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        tlbProfessores.add(btnAdicionar);

        add(tlbProfessores);

        tblProfessores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProfessores.setColumnSelectionAllowed(true);
        tblProfessores.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblProfessores);
        tblProfessores.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        frmEditProfessor editProfessor = new frmEditProfessor("Novo Professor");
        editProfessor.setVisible(true);
    }//GEN-LAST:event_btnAdicionarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProfessores;
    private javax.swing.JToolBar tlbProfessores;
    // End of variables declaration//GEN-END:variables
}
