/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmTurma.java
 *
 * Created on 19/06/2011, 18:31:48
 */
package presenca;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import javax.swing.JFileChooser;

/**
 *
 * @author diego
 */
public class frmTurma extends javax.swing.JPanel {
    Turma turma;
    dlgEditTurma editTurma;
    
    /** Creates new form frmTurma */
    public frmTurma() {
        initComponents();
        
        turma = new Turma();
        generateTable();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tlbAlunos = new javax.swing.JToolBar();
        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnGerarLista = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTurmas = new javax.swing.JTable();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        tlbAlunos.setRollover(true);
        tlbAlunos.setMaximumSize(new java.awt.Dimension(32767, 30));

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presenca/resources/add.png"))); // NOI18N
        btnAdicionar.setText(" Adicionar ");
        btnAdicionar.setBorder(null);
        btnAdicionar.setFocusable(false);
        btnAdicionar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdicionar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        tlbAlunos.add(btnAdicionar);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presenca/resources/edit.png"))); // NOI18N
        btnEditar.setText(" Editar ");
        btnEditar.setBorder(null);
        btnEditar.setFocusable(false);
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        tlbAlunos.add(btnEditar);

        btnRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presenca/resources/delete.png"))); // NOI18N
        btnRemover.setText(" Remover ");
        btnRemover.setBorder(null);
        btnRemover.setFocusable(false);
        btnRemover.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRemover.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        tlbAlunos.add(btnRemover);

        btnGerarLista.setText("Gerar Lista");
        btnGerarLista.setFocusable(false);
        btnGerarLista.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGerarLista.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGerarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarListaActionPerformed(evt);
            }
        });
        tlbAlunos.add(btnGerarLista);

        add(tlbAlunos);

        tblTurmas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Disciplina", "Professor", "Ano", "Semestre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTurmas.setColumnSelectionAllowed(true);
        tblTurmas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblTurmas);
        tblTurmas.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        editTurma = new dlgEditTurma(null,"Nova Turma");
        editTurma.setVisible(true);
        generateTable();
}//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        Integer idTurma = tblTurmas.getSelectedRow();
        if(idTurma >= 0){
            Integer id = (Integer)tblTurmas.getValueAt(idTurma, 0);
            
            editTurma = new dlgEditTurma(null, "Editar Turma", id);
            editTurma.setVisible(true);
            generateTable();
        }else{
            JOptionPane.showMessageDialog(this, "Nenhum item foi selecionado.");
        }
}//GEN-LAST:event_btnEditarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        Integer idTurma = tblTurmas.getSelectedRow();
        if(idTurma >= 0){
            Integer id = (Integer)tblTurmas.getValueAt(idTurma, 0);
            
            int result = JOptionPane.showConfirmDialog(this,
                    "A ação de remoção não poderá ser desfeita.\nDeseja prosseguir?",
                    "Deseja remover a turma?",
                    0);
            if(result == 0){
                turma = new Turma(id);
                turma.destroy();
                generateTable();
            }
            
        }else{
            JOptionPane.showMessageDialog(this, "Nenhum item foi selecionado.");
        }
}//GEN-LAST:event_btnRemoverActionPerformed

    private void btnGerarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarListaActionPerformed
        Integer idTurma = tblTurmas.getSelectedRow();
        if(idTurma >= 0){
            Integer id = (Integer)tblTurmas.getValueAt(idTurma, 0);
            turma = new Turma(id);
            
            ArrayList<Aluno> alunos = new ArrayList<Aluno>();
            AlunoTurma at = new AlunoTurma();
            Aluno a;
            
            ArrayList<Integer> alunoIds = at.allId("idTurma = " + id);
            for(Integer ai: alunoIds){
                at = new AlunoTurma(ai);
                alunos.add(new Aluno(at.getIdAluno()));
            }
            
            ListaChamada lc = new ListaChamada("src/presenca/resources/template.svg");
            lc.setProfessor(turma.getProfessor());
            lc.setAlunos(alunos);
            
            JFileChooser fc = new JFileChooser();
            
            int returnVal = fc.showSaveDialog(this);
            if(returnVal == JFileChooser.APPROVE_OPTION) {
                String output = fc.getCurrentDirectory().toString();
                output += "/"+fc.getSelectedFile().getName();
                System.out.println(output);
                lc.setOutput(output);
                lc.saveOutput();
            }
            
            
            
            generateTable();
        }else{
            JOptionPane.showMessageDialog(this, "Nenhum item foi selecionado.");
        }
    }//GEN-LAST:event_btnGerarListaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGerarLista;
    private javax.swing.JButton btnRemover;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTurmas;
    private javax.swing.JToolBar tlbAlunos;
    // End of variables declaration//GEN-END:variables
    private void generateTable(){
        DefaultTableModel mdlModel = (DefaultTableModel)tblTurmas.getModel();
        
        int i;
        for(i = mdlModel.getRowCount() - 1; i >= 0; i-- ){
            mdlModel.removeRow(i);
        }
        
        Object contents[] = new Object[5];
        
        for(Integer id: turma.allId("")){
            turma = new Turma(id);
            
            contents[0] = id;
            contents[1] = turma.getDisciplina().getNome();
            contents[2] = turma.getProfessor().getNome();
            contents[3] = turma.getAno();
            contents[4] = turma.getSemestre();
            
            mdlModel.addRow(contents);
        }
    }
}
