/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * winMain.java
 *
 * Created on Jun 3, 2011, 3:25:29 PM
 */
package presenca;

import javax.swing.JPanel;

/**
 *
 * @author drubin
 */
public class winMain extends javax.swing.JFrame {

    /** Creates new form winMain */
    public winMain() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frmContent = new javax.swing.JPanel();
        mnbMain = new javax.swing.JMenuBar();
        mnArquivo = new javax.swing.JMenu();
        mnSair = new javax.swing.JMenuItem();
        mnAlunos = new javax.swing.JMenu();
        mnGerenciarAlunos = new javax.swing.JMenuItem();
        mnProfessores = new javax.swing.JMenu();
        mnGerenciarProfessores = new javax.swing.JMenuItem();
        mnTurmas = new javax.swing.JMenu();
        mnGerenciarTurma = new javax.swing.JMenuItem();
        mnGerenciarDisciplinas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Presença - Gestão de Alunos");
        setLocationByPlatform(true);
        setName("frmMain"); // NOI18N
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        frmContent.setLayout(new java.awt.GridLayout());
        getContentPane().add(frmContent);

        mnArquivo.setText("Arquivo");

        mnSair.setText("Sair");
        mnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSairActionPerformed(evt);
            }
        });
        mnArquivo.add(mnSair);

        mnbMain.add(mnArquivo);

        mnAlunos.setText("Alunos");

        mnGerenciarAlunos.setText("Gerenciar");
        mnGerenciarAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnGerenciarAlunosActionPerformed(evt);
            }
        });
        mnAlunos.add(mnGerenciarAlunos);

        mnbMain.add(mnAlunos);

        mnProfessores.setText("Professores");

        mnGerenciarProfessores.setText("Gerenciar");
        mnGerenciarProfessores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnGerenciarProfessoresActionPerformed(evt);
            }
        });
        mnProfessores.add(mnGerenciarProfessores);

        mnbMain.add(mnProfessores);

        mnTurmas.setText("Turmas");

        mnGerenciarTurma.setText("Gerenciar Turmas");
        mnGerenciarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnGerenciarTurmaActionPerformed(evt);
            }
        });
        mnTurmas.add(mnGerenciarTurma);

        mnGerenciarDisciplinas.setText("Gerenciar Disciplinas");
        mnTurmas.add(mnGerenciarDisciplinas);

        mnbMain.add(mnTurmas);

        setJMenuBar(mnbMain);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnSairActionPerformed

    private void mnGerenciarProfessoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnGerenciarProfessoresActionPerformed
        frmContent.removeAll();
        frmContent.add(new frmProfessor()); 
        frmContent.validate(); 
    }//GEN-LAST:event_mnGerenciarProfessoresActionPerformed

    private void mnGerenciarAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnGerenciarAlunosActionPerformed
        frmContent.removeAll();
        frmContent.add(new frmAluno());
        frmContent.validate(); 
    }//GEN-LAST:event_mnGerenciarAlunosActionPerformed

    private void mnGerenciarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnGerenciarTurmaActionPerformed
        frmContent.removeAll();
        frmContent.add(new frmTurma());
        frmContent.validate(); 
    }//GEN-LAST:event_mnGerenciarTurmaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new winMain().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel frmContent;
    private javax.swing.JMenu mnAlunos;
    private javax.swing.JMenu mnArquivo;
    private javax.swing.JMenuItem mnGerenciarAlunos;
    private javax.swing.JMenuItem mnGerenciarDisciplinas;
    private javax.swing.JMenuItem mnGerenciarProfessores;
    private javax.swing.JMenuItem mnGerenciarTurma;
    private javax.swing.JMenu mnProfessores;
    private javax.swing.JMenuItem mnSair;
    private javax.swing.JMenu mnTurmas;
    private javax.swing.JMenuBar mnbMain;
    // End of variables declaration//GEN-END:variables
}
